Make rust decoder default (#1375)
* Use rust by default and add -WITHOUT_RUST flag

* Fix for shell and autoconf builds

* change directory for version check

* change to  staticlib

* Update windows to build rust

* fix formatting

* add information about 708 decoder in version flag

* revert file mode to 644

* Use x86 for OCR releases

* fix flushing bug

* fix formatting

* update lib names

* remove bazel

* update changelog

diff --git a/linux/build b/linux/build
--- a/linux/build
+++ b/linux/build
@@ -61,6 +61,22 @@ echo "Running pre-build script..."
 ./pre-build.sh
 echo "Trying to compile..."
 
+if [ "$1" = "-without-rust" ]; then
+    echo "Building without rust files..."
+    BLD_FLAGS="$BLD_FLAGS -DDISABLE_RUST"
+else 
+    BLD_LINKER="$BLD_LINKER ./libccx_rust.a"
+    echo "Checking for cargo..."
+    if ! [ -x "$(command -v cargo)" ]; then
+        echo 'Error: cargo is not installed.' >&2
+        exit 1
+    fi
+    echo "Building rust files..."
+    (cd ../src/rust && CARGO_TARGET_DIR=../../linux/rust cargo build )
+    cp rust/debug/libccx_rust.a ./libccx_rust.a
+fi
+
+echo "Building ccextractor"
 out=$((LC_ALL=C gcc $BLD_FLAGS $BLD_INCLUDE -o ccextractor $BLD_SOURCES $BLD_LINKER)2>&1)
 res=$?
 if [[ $out == *"gcc: command not found"* ]]
